jakartaee/interceptors

pom.xml

Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>

Changed groupId and artifactId. Fixes #6 (master)

---

pom.xml

Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>

Changed groupId and artifactId. Fixes #9 (EE4J)

---

pom.xml

Update pom to 1.0.2, remove CDDL license, release and doc plugin

---

pom.xml

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

Update jakarta artifacts, update parent to 1.0.4.

---

pom.xml

Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>

Update parent pom to 1.0.5

---

api/pom.xml
api/src/main/java/javax/interceptor/AroundConstruct.java
api/src/main/java/javax/interceptor/AroundInvoke.java
api/src/main/java/javax/interceptor/AroundTimeout.java
api/src/main/java/javax/interceptor/ExcludeClassInterceptors.java
api/src/main/java/javax/interceptor/ExcludeDefaultInterceptors.java
api/src/main/java/javax/interceptor/Interceptor.java
api/src/main/java/javax/interceptor/InterceptorBinding.java
api/src/main/java/javax/interceptor/Interceptors.java
api/src/main/java/javax/interceptor/InvocationContext.java
api/src/main/java/javax/interceptor/package.html
pom.xml

Fix poms and javadoc

---

api/pom.xml
pom.xml
spec/pom.xml

Prepare for 1.2.5 release

---

api/pom.xml
pom.xml

#34 Independent API module

---

api/pom.xml

Update to Jakarta EJB 3.2.6

---

api/pom.xml

Update to latest Jakarta dependencies

---

api/pom.xml
api/src/main/javadoc/doc-files/speclicense.html

Update Javadoc for latest Jakarta EE 8 requirements

---

spec/src/main/asciidoc/interceptors-spec.adoc

Update Javadoc doctitle to exclude version number

---

spec/src/main/asciidoc/license-efsl.adoc

Added Eclipse copyright to spec doc

---

api/pom.xml

Merge final release branch for 1.2.5

---

api/pom.xml
api/src/main/java/javax/interceptor/InvocationContext.java

Removed link to EJB javadoc and dependency

---

api/pom.xml
api/src/main/java/jakarta/interceptor/AroundConstruct.java
api/src/main/java/jakarta/interceptor/AroundInvoke.java
api/src/main/java/jakarta/interceptor/AroundTimeout.java
api/src/main/java/jakarta/interceptor/ExcludeClassInterceptors.java
api/src/main/java/jakarta/interceptor/ExcludeDefaultInterceptors.java
api/src/main/java/jakarta/interceptor/Interceptor.java
api/src/main/java/jakarta/interceptor/InterceptorBinding.java
api/src/main/java/jakarta/interceptor/Interceptors.java
api/src/main/java/jakarta/interceptor/InvocationContext.java
api/src/main/java/jakarta/interceptor/package.html
pom.xml

Signed-off-by: Scott Marlow <smarlow@redhat.com>

javax.interceptor to jakarta.interceptor

---

api/pom.xml
pom.xml
spec/pom.xml

Formatting of poms

---

api/pom.xml

EE4J parent to 1.0.6 for API

---

api/pom.xml
pom.xml
spec/pom.xml

#53 Prepare for RC1

---

api/pom.xml

#53 update Common Annotations to 2.0.0-RC1

---

api/pom.xml
pom.xml
spec/pom.xml

#53 Prepare for RC2 release

---

api/pom.xml
pom.xml
spec/pom.xml

* Tidying
* Updated versions
* Main version back to snapshot
* Removed unused release plugin

Small pom cleanup

---

api/pom.xml
api/src/main/java/jakarta/interceptor/AroundConstruct.java
api/src/main/java/jakarta/interceptor/AroundInvoke.java
api/src/main/java/jakarta/interceptor/AroundTimeout.java
api/src/main/java/jakarta/interceptor/ExcludeClassInterceptors.java
api/src/main/java/jakarta/interceptor/ExcludeDefaultInterceptors.java
api/src/main/java/jakarta/interceptor/Interceptor.java
api/src/main/java/jakarta/interceptor/InterceptorBinding.java
api/src/main/java/jakarta/interceptor/Interceptors.java
api/src/main/java/jakarta/interceptor/InvocationContext.java
api/src/main/java/jakarta/interceptor/package.html
api/src/main/javadoc/doc-files/speclicense.html
pom.xml
spec/README.md
spec/pom.xml
spec/src/main/asciidoc/0_license_efsl.adoc
spec/src/main/asciidoc/1_overview.adoc
spec/src/main/asciidoc/2_interceptor_programming_contract.adoc
spec/src/main/asciidoc/3_associating_interceptors_with_classes_and_methods_using_interceptor_bindings.adoc
spec/src/main/asciidoc/4_associating_interceptors_with_classes_and_methods_using_the_interceptors_annotation.adoc
spec/src/main/asciidoc/5_interceptor_ordering.adoc
spec/src/main/asciidoc/a_bibliography.adoc
spec/src/main/asciidoc/b_change_log.adoc
spec/src/main/asciidoc/interceptors-spec.adoc

Updated for final release

---

api/src/main/java/jakarta/interceptor/InvocationContext.java
pom.xml
spec/pom.xml

Javadoc Jakarta update and pom version update

---

api/pom.xml
spec/pom.xml

Update versions in poms

---

api/pom.xml

Administrative merge to finish https://github.com/eclipse-ee4j/interceptor-api/issues/82

Merge 2.0.0 release branch

---

api/pom.xml
api/src/main/javadoc/doc-files/speclicense.html
pom.xml
spec/pom.xml

Update dependency versions and tab to spaces

---

api/pom.xml
pom.xml
spec/pom.xml

Update version to 2.1 and set to JDK 11 as minimum

---

api/pom.xml
pom.xml
spec/pom.xml

This reverts commit 2e38858aaf09f12a0090dcfb13caeeef1e900c03.

Revert "Update version to 2.1 and set to JDK 11 as minimum"

---

api/pom.xml

Signed-off-by: Scott M Stark <starksm64@gmail.com>

Need to rollback jakarta.annotation-api to 2.1.0-B1 for public RC release

---

api/pom.xml

This should fix the current release problems

Update parent pom to 1.0.9 and disable the check-module goal for now

---

.gitignore
api/pom.xml
pom.xml
spec/pom.xml

Specifically parent pom to 1.0.9 and using 3.0.0-M1 dependency for annotations.

Update versions in poms to latest versions

---

api/pom.xml

Set Jakarta Annotations dependency to the final 3.0.0
